In [5]:
from apyori import apriori

import pandas as pd

# Data Preprocessing
df = pd.read_csv("C:\\Users\\sujey\\Downloads\\Assignments\\Association Rules\\Association Rules\\Online retail.csv", header = None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
trans = []

for i in range(0, 7501):
  trans.append([str(df.values[i,j]) for j in range(0, 20)])

In [7]:
assoc_rules = apriori(transactions = trans,min_support = 0.003,min_confidence = 0.2,min_lift = 3,min_length = 2,max_length = 2)

In [8]:
final_op = list(assoc_rules)
final_op

[RelationRecord(items=frozenset({'light cream', 'chicken'}), support=0.004532728969470737, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)]),
 RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]),
 RelationRecord(items=frozenset({'escalope', 'pasta'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)]),
 RelationRecord(items=frozenset({'fromage blanc', 'honey'}), support=0.003332888948140248, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.164270764485569)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]),
 RelationRecord(items=frozenset({'ground beef', 'tomato sauce'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3773584905660377, lift=3.840659481324083)]),
 RelationRecord(items=frozenset({'light cream', 'olive oil'}), support=0.003199573390214638, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820515, lift=3.1147098515519573)]),
 RelationRecord(items=frozenset({'whole wheat pasta', 'olive oil'}), support=0.007998933475536596, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.122410097642296)]),
 RelationRecord(items=frozenset({'shrimp', 'pasta'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050847, lift=4.506672147735896)])]

0.29059829059829057

In [15]:
a=[]
b=[]
c=[]
d=[]
e=[]

for i in range(0,9):
    a.append(final_op[i][2][0][0])
    b.append(final_op[i][2][0][1])
    c.append(final_op[i][1])
    d.append(final_op[i][2][0][2])
    e.append(final_op[i][2][0][3])

a = pd.DataFrame(a)
b = pd.DataFrame(b)
c = pd.DataFrame(c)
d = pd.DataFrame(d)
e = pd.DataFrame(e)

In [16]:
final_df = pd.concat([a,b,c,d,e],axis=1)
final_df.columns = ["Base","Add","Support","Confidence","Lift"]
final_df

                   Base          Add   Support  Confidence      Lift
0           light cream      chicken  0.004533    0.290598  4.843951
1  mushroom cream sauce     escalope  0.005733    0.300699  3.790833
2                 pasta     escalope  0.005866    0.372881  4.700812
3         fromage blanc        honey  0.003333    0.245098  5.164271
4         herb & pepper  ground beef  0.015998    0.323450  3.291994
5          tomato sauce  ground beef  0.005333    0.377358  3.840659
6           light cream    olive oil  0.003200    0.205128  3.114710
7     whole wheat pasta    olive oil  0.007999    0.271493  4.122410
8                 pasta       shrimp  0.005066    0.322034  4.506672

In [ ]:
#1.	What is lift and why is it important in Association rules?
#   Lift is important in association rules as it hepls us find how much the sales of one product increases due to the other product
#2.	What is support and Confidence. How do you calculate them?
# Support is find individual probabities of the items. While confidence is how much % confident we are that a person will buy product 2 if he purchased 
#product 1.
# Calculation:
#Support = P(A)/P(Total)
#Confidence = P(A/B) = P(Aâˆ©B)/P(B)
#3.	What are some limitations or challenges of Association rules mining?
# The limitations are:
# 1) One major challenge is the potential for irrelevant or trivial rules, especially when dealing with large datasets or setting inappropriate 
#    thresholds for support and confidence
# 2) Other challenges include computational complexity, especially for large datasets, and the difficulty of interpreting the results, especially when 
#    dealing with complex relationships or sparse data.